const USER_ACTION_TYPES={
    GET_USER_DETAILS_LOADING:"GET_USER_DETAILS_LOADING",
    GET_USER_DETAILS_DATA:"GET_USER_DETAILS_DATA",

    POST_USER_DETAILS_LOADING:"POST_USER_DETAILS_LOADING",
    POST_USER_DETAILS_RESET:"POST_USER_DETAILS_RESET",
    POST_USER_DETAILS_DATA:"POST_USER_DETAILS_DATA",

    EDIT_USER_DETAILS_LOADING:"EDIT_USER_DETAILS_LOADING",
    EDIT_USER_DETAILS_DATA:"EDIT_USER_DETAILS_DATA",

    DELETE_USER_DETAILS_LOADING:"DELETE_USER_DETAILS_LOADING",
    DELETE_USER_DETAILS_DATA:"DELETE_USER_DETAILS_DATA",
}
export default USER_ACTION_TYPES